sudo: required
services:
  - docker

language: elixir
elixir:
  - 1.6
otp_release:
  - 20.1

before_deploy:
  - MIX_ENV=prod mix release
  - cd assets && npm run build; cd ../
  - MIX_ENV=prod mix phx.digest

deploy:
  provider: script
  script: docker/publish.sh
  skip_cleanup: true
  on:
    tags: true
